### ISSUE TITLE
Full release URL

### ISSUE THREAD

**Issue by fulldecent** [walshie4/Ultimate-Blocklist#16]
Perhaps include a URL which can be pasted directly into Transmission, for mere users of the project.

**Comment by scannermobs** [comment]
+1 to this suggestion. Needlessly complex, if I understand correctly, when most people here are just after a simple URL

**Comment by walshie4** [comment]
It's in the README, but was not very clear.  Sorry about that! Let me know if this doesn't work.

`https://www.dropbox.com/s/2f8irg93zgglh2d/blocklist.txt?dl=1`

**Comment by scannermobs** [comment]
That's brilliant, cheers Adam
